// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Node struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Status     string         `json:"status"`
	TokenHash  string         `json:"token_hash"`
	SystemInfo sql.NullString `json:"system_info"`
	TokenUsed  bool           `json:"token_used"`
	LastSeenAt sql.NullTime   `json:"last_seen_at"`
	CreatedAt  time.Time      `json:"created_at"`
}

type NodeReport struct {
	ID         int64     `json:"id"`
	NodeID     string    `json:"node_id"`
	Payload    string    `json:"payload"`
	ReportedAt time.Time `json:"reported_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
