// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (id, name, platform, status, token_hash) VALUES (?, ?, ?, ?, ?)
RETURNING id, name, platform, status, token_hash, system_info, token_used, last_seen_at, created_at
`

type CreateNodeParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Platform  string `json:"platform"`
	Status    string `json:"status"`
	TokenHash string `json:"token_hash"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.Platform,
		arg.Status,
		arg.TokenHash,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.Status,
		&i.TokenHash,
		&i.SystemInfo,
		&i.TokenUsed,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNodeReport = `-- name: CreateNodeReport :one
INSERT INTO node_reports (node_id, payload) VALUES (?, ?) RETURNING id, node_id, payload, reported_at
`

type CreateNodeReportParams struct {
	NodeID  string `json:"node_id"`
	Payload string `json:"payload"`
}

func (q *Queries) CreateNodeReport(ctx context.Context, arg CreateNodeReportParams) (NodeReport, error) {
	row := q.db.QueryRowContext(ctx, createNodeReport, arg.NodeID, arg.Payload)
	var i NodeReport
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Payload,
		&i.ReportedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash) VALUES (?, ?) RETURNING id, username, password_hash, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, name, platform, status, token_hash, system_info, token_used, last_seen_at, created_at FROM nodes WHERE id = ? LIMIT 1
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.Status,
		&i.TokenHash,
		&i.SystemInfo,
		&i.TokenUsed,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at FROM users WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, platform, status, token_hash, system_info, token_used, last_seen_at, created_at FROM nodes ORDER BY created_at DESC
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.Status,
			&i.TokenHash,
			&i.SystemInfo,
			&i.TokenUsed,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleOnlineNodes = `-- name: ListStaleOnlineNodes :many
SELECT id, name, platform, status, token_hash, system_info, token_used, last_seen_at, created_at FROM nodes WHERE status = 'online' AND (last_seen_at IS NULL OR last_seen_at < ?) ORDER BY created_at DESC
`

func (q *Queries) ListStaleOnlineNodes(ctx context.Context, lastSeenAt sql.NullTime) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listStaleOnlineNodes, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.Status,
			&i.TokenHash,
			&i.SystemInfo,
			&i.TokenUsed,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstallTokenUsed = `-- name: MarkInstallTokenUsed :exec
UPDATE nodes SET token_used = TRUE WHERE id = ?
`

func (q *Queries) MarkInstallTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markInstallTokenUsed, id)
	return err
}

const markNodeOffline = `-- name: MarkNodeOffline :exec
UPDATE nodes SET status = 'offline' WHERE id = ? AND status = 'online'
`

func (q *Queries) MarkNodeOffline(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markNodeOffline, id)
	return err
}

const rotateInstallToken = `-- name: RotateInstallToken :one
UPDATE nodes SET token_hash = ?, token_used = FALSE WHERE id = ?
RETURNING id, name, platform, status, token_hash, system_info, token_used, last_seen_at, created_at
`

type RotateInstallTokenParams struct {
	TokenHash string `json:"token_hash"`
	ID        string `json:"id"`
}

func (q *Queries) RotateInstallToken(ctx context.Context, arg RotateInstallTokenParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, rotateInstallToken, arg.TokenHash, arg.ID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.Status,
		&i.TokenHash,
		&i.SystemInfo,
		&i.TokenUsed,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateNodeStatus = `-- name: UpdateNodeStatus :exec
UPDATE nodes SET status = ?, last_seen_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateNodeStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeStatus, arg.Status, arg.ID)
	return err
}

const updateNodeSystemInfo = `-- name: UpdateNodeSystemInfo :exec
UPDATE nodes SET system_info = ?, last_seen_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateNodeSystemInfoParams struct {
	SystemInfo sql.NullString `json:"system_info"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateNodeSystemInfo(ctx context.Context, arg UpdateNodeSystemInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeSystemInfo, arg.SystemInfo, arg.ID)
	return err
}
